[workspace]
authors = ["Rabeez Riaz <ruoter123@gmail.com>"]
channels = ["conda-forge"]
name = "cosmere_analysis"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
nvim = "nvim"
get_characters = "python src/get_characters.py"
books = "python src/parse_books.py"
cooccurence = "python src/make_cooccurence.py"
network = "python src/make_json_network.py"
dev = "python -m http.server"

[dependencies]
python = "3.12.*"
pip = ">=25.1.1,<26"
polars = ">=1.29.0,<2"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"
numpy = ">=2.2.5,<3"
scipy = ">=1.15.2,<2"
python-dotenv = ">=1.1.0,<2"
httpx = ">=0.28.1,<0.29"
selectolax = ">=0.3.29,<0.4"
tqdm = ">=4.67.1,<5"
ipykernel = ">=6.29.5,<7"
spacy = ">=3.8.5,<4"
